---
# Build definitions for `build.py`

# DEB packages
debian:
  releases:
    bullseye: '11'
    bookworm: '12'
  archmaps:
    amd64:
      PACKAGE_ARCH: amd64
    arm64:
      PACKAGE_ARCH: arm64
    armhf:
      PACKAGE_ARCH: armhf
  cross-gcc:
    bullseye: '10'
    bookworm: '12'
  build_function: build_package_deb
  dockerfile: debian/docker/Dockerfile
  imagename: jellyfin-builder-debian
ubuntu:
  releases:
    focal: '20.04'
    jammy: '22.04'
    noble: '24.04'
  archmaps:
    amd64:
      PACKAGE_ARCH: amd64
    arm64:
      PACKAGE_ARCH: arm64
    armhf:
      PACKAGE_ARCH: armhf
  cross-gcc:
    focal: '10'
    jammy: '12'
    noble: '13'
  build_function: build_package_deb
  dockerfile: debian/docker/Dockerfile
  imagename: jellyfin-builder-ubuntu

# Portable archives
linux:
  build_function: build_linux
  archivetypes: targz,tarxz
  archmaps:
    amd64:
      DOTNET_ARCH: x64
      PACKAGE_ARCH: amd64
    amd64-musl:
      DOTNET_ARCH: musl-x64
      PACKAGE_ARCH: amd64-musl
    arm64:
      DOTNET_ARCH: arm64
      PACKAGE_ARCH: arm64
    arm64-musl:
      DOTNET_ARCH: musl-arm64
      PACKAGE_ARCH: arm64-musl
    armhf:
      DOTNET_ARCH: arm
      PACKAGE_ARCH: armhf
  dockerfile: portable/Dockerfile
  imagename: jellyfin-builder-linux
windows:
  build_function: build_windows
  archivetypes: zip
  archmaps:
    amd64:
      DOTNET_ARCH: x64
      PACKAGE_ARCH: amd64
    arm64:
      DOTNET_ARCH: arm64
      PACKAGE_ARCH: arm64
  dockerfile: portable/Dockerfile
  imagename: jellyfin-builder-windows
macos:
  build_function: build_macos
  archivetypes: tarxz
  archmaps:
    amd64:
      DOTNET_ARCH: x64
      PACKAGE_ARCH: amd64
    arm64:
      DOTNET_ARCH: arm64
      PACKAGE_ARCH: arm64
  dockerfile: portable/Dockerfile
  imagename: jellyfin-builder-macos
portable:
  build_function: build_portable
  archivetypes: targz,tarxz,zip
  dockerfile: portable/Dockerfile
  imagename: jellyfin-builder-portable

# Docker images
docker:
  build_function: build_docker
  archmaps:
    amd64:
      DOTNET_ARCH: x64
      IMAGE_ARCH: amd64
      PACKAGE_ARCH: amd64
      QEMU_ARCH: x86_64
    arm64:
      DOTNET_ARCH: arm64
      IMAGE_ARCH: arm64v8
      PACKAGE_ARCH: arm64
      QEMU_ARCH: aarch64
    armhf:
      DOTNET_ARCH: arm
      IMAGE_ARCH: arm32v7
      PACKAGE_ARCH: armhf
      QEMU_ARCH: arm
  dockerfile: docker/Dockerfile
  imagename: ocd0711/jellyfin

# Nuget packages
nuget:
  build_function: build_nuget
  projects:
    - Jellyfin.Data/Jellyfin.Data.csproj
    - MediaBrowser.Common/MediaBrowser.Common.csproj
    - MediaBrowser.Controller/MediaBrowser.Controller.csproj
    - MediaBrowser.Model/MediaBrowser.Model.csproj
    - Emby.Naming/Emby.Naming.csproj
    - src/Jellyfin.Extensions/Jellyfin.Extensions.csproj
  feed_urls:
    stable: https://api.nuget.org/v3/index.json
    unstable: https://nuget.pkg.github.com/jellyfin/index.json
